# Generated by Django 3.1.3 on 2020-11-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('symptoms', models.CharField(max_length=80)),
                ('diagnosis', models.CharField(max_length=30)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.PositiveIntegerField()),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors_auth.doctorprofile')),
            ],
        ),
    ]
