# Generated by Django 3.0.8 on 2020-11-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='signed_out',
        ),
    ]
