# Generated by Django 3.1.3 on 2020-11-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='users'),
        ),
    ]
