# Generated by Django 3.0.8 on 2020-07-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('specialty', models.CharField(choices=[('Urologist', 'Urologist'), ('Gynecologist', 'Gynecologist'), ('Dermatologist', 'Dermatologist'), ('Nephrologist', 'Nephrologist'), ('Endocrinologist', 'Endocrinologist'), ('Cardiologist', 'Cardiologist'), ('Virologist', 'Virologist'), ('Surgeon', 'Surgeon')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.UserProfile')),
            ],
        ),
    ]
